import type { VoiceProfile } from '../types';

export function createProfileCardDataUrl(input: { title: string; summary: string; profile: VoiceProfile }): string {
  const canvas = document.createElement('canvas');
  canvas.width = 900;
  canvas.height = 520;
  const ctx = canvas.getContext('2d');
  if (!ctx) return '';

  const gradient = ctx.createLinearGradient(0, 0, 900, 520);
  gradient.addColorStop(0, '#0f172a');
  gradient.addColorStop(1, '#0e7490');
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, 900, 520);

  ctx.fillStyle = 'rgba(255,255,255,0.1)';
  ctx.fillRect(32, 32, 836, 456);

  ctx.fillStyle = '#ffffff';
  ctx.font = '700 42px Space Grotesk, sans-serif';
  ctx.fillText(input.title, 60, 95);

  ctx.font = '500 24px Space Grotesk, sans-serif';
  ctx.fillText(input.summary.slice(0, 50), 60, 145);

  const metrics: Array<{ label: string; value: number; color: string }> = [
    { label: '밝음', value: input.profile.brightness, color: '#f59e0b' },
    { label: '허스키', value: input.profile.husky, color: '#06b6d4' },
    { label: '부드러움', value: input.profile.softness, color: '#10b981' },
  ];

  metrics.forEach((metric, index) => {
    const y = 220 + index * 90;
    const percent = Math.round(Math.max(0, Math.min(1, metric.value)) * 100);

    ctx.fillStyle = '#e2e8f0';
    ctx.fillRect(210, y - 18, 560, 30);

    ctx.fillStyle = metric.color;
    ctx.fillRect(210, y - 18, (560 * percent) / 100, 30);

    ctx.fillStyle = '#ffffff';
    ctx.font = '600 22px Space Grotesk, sans-serif';
    ctx.fillText(metric.label, 60, y + 4);
    ctx.fillText(`${percent}%`, 790, y + 4);
  });

  ctx.font = '500 16px Space Grotesk, sans-serif';
  ctx.fillStyle = 'rgba(255,255,255,0.9)';
  ctx.fillText('Generated by VoiceFit', 60, 470);

  return canvas.toDataURL('image/png');
}
