import type { VoiceProfile } from '../types';

export function createProfileCardDataUrl(input: { title: string; summary: string; profile: VoiceProfile }): string {
  const canvas = document.createElement('canvas');
  canvas.width = 1080;
  canvas.height = 1080;
  const ctx = canvas.getContext('2d');
  if (!ctx) return '';

  const gradient = ctx.createLinearGradient(0, 0, 1080, 1080);
  gradient.addColorStop(0, '#0f172a');
  gradient.addColorStop(1, '#164e63');
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, 1080, 1080);

  ctx.fillStyle = 'rgba(255,255,255,0.06)';
  ctx.beginPath();
  ctx.arc(920, 140, 180, 0, Math.PI * 2);
  ctx.fill();
  ctx.beginPath();
  ctx.arc(140, 960, 210, 0, Math.PI * 2);
  ctx.fill();

  ctx.fillStyle = 'rgba(255,255,255,0.94)';
  ctx.fillRect(72, 72, 936, 936);

  ctx.fillStyle = '#0f172a';
  ctx.font = '700 56px Space Grotesk, sans-serif';
  ctx.fillText(input.title, 130, 180);
  ctx.fillStyle = '#0891b2';
  ctx.font = '700 24px Space Grotesk, sans-serif';
  ctx.fillText('VOICE PROFILE CARD', 130, 226);

  ctx.fillStyle = '#334155';
  ctx.font = '500 28px Space Grotesk, sans-serif';
  const summary = input.summary.trim().length > 0 ? input.summary.trim() : '나만의 음색 프로필 분석 결과';
  const summaryLines = wrapText(ctx, summary, 820);
  summaryLines.slice(0, 2).forEach((line, index) => {
    ctx.fillText(line, 130, 284 + index * 38);
  });

  const metrics: Array<{ label: string; value: number; color: string }> = [
    { label: 'Bright', value: input.profile.brightness, color: '#0ea5e9' },
    { label: 'Husky', value: input.profile.husky, color: '#14b8a6' },
    { label: 'Soft', value: input.profile.softness, color: '#22c55e' },
  ];

  metrics.forEach((metric, index) => {
    const y = 430 + index * 168;
    const percent = Math.round(Math.max(0, Math.min(1, metric.value)) * 100);

    ctx.fillStyle = '#e2e8f0';
    ctx.fillRect(130, y, 820, 38);

    const barGradient = ctx.createLinearGradient(130, y, 950, y + 38);
    barGradient.addColorStop(0, metric.color);
    barGradient.addColorStop(1, '#0284c7');
    ctx.fillStyle = barGradient;
    ctx.fillRect(130, y, (820 * percent) / 100, 38);

    ctx.fillStyle = '#0f172a';
    ctx.font = '700 30px Space Grotesk, sans-serif';
    ctx.fillText(metric.label, 130, y - 24);

    ctx.fillStyle = '#0369a1';
    ctx.font = '700 32px Space Grotesk, sans-serif';
    ctx.fillText(`${percent}%`, 868, y - 24);
  });

  ctx.fillStyle = '#64748b';
  ctx.font = '600 24px Space Grotesk, sans-serif';
  ctx.fillText('Generated by VoiceFit', 130, 960);

  ctx.fillStyle = '#0f172a';
  ctx.font = '700 30px Space Grotesk, sans-serif';
  ctx.fillText(new Date().toISOString().slice(0, 10), 790, 960);

  return canvas.toDataURL('image/png');
}

function wrapText(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = '';

  words.forEach((word) => {
    const candidate = current ? `${current} ${word}` : word;
    if (ctx.measureText(candidate).width <= maxWidth) {
      current = candidate;
      return;
    }
    if (current) lines.push(current);
    current = word;
  });

  if (current) lines.push(current);
  return lines;
}
